### auth login
### POST /api/auth/login
POST http://127.0.0.1:3000/api/auth/login
content-type: application/json

{
    "username": "JohnDoe",
    "password": "to-be-hashed-pw1"
}

### GET my user info
GET http://127.0.0.1:3000/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6IkpvaG5Eb2UiLCJlbWFpbCI6ImpvaG5kb2VAZXhhbXBsZS5jb20iLCJ1c2VyX2xldmVsX2lkIjoyLCJpYXQiOjE3MDA2NDU0ODh9.gNZq5Qw8t7hZ1UM1-ffqe9oiXkVxfRUYxYjaNtt-fA0

### GET / 
GET http://127.0.0.1:3000/

### GET /medias
GET http://127.0.0.1:3000/api/media

### GET /media/:id
GET http://127.0.0.1:3000/api/media/8

### POST /media
POST http://127.0.0.1:3000/api/media
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6IkpvaG5Eb2UiLCJlbWFpbCI6ImpvaG5kb2VAZXhhbXBsZS5jb20iLCJ1c2VyX2xldmVsX2lkIjoyLCJpYXQiOjE3MDA2NDUxMDN9.FK9V6YOw8BOYjiRW2R6irkb3S0NM3X5gdwB5sKRv61U
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="title"

New media title

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="description"

New media description

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="image.jpg"
Content-Type: image/jpeg

 ./image.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### POST /media error
POST http://127.0.0.1:3000/api/media

{"höpö": "höpö"}

### PUT /media/:id
PUT http://127.0.0.1:3000/api/media/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6IkpvaG5Eb2UiLCJlbWFpbCI6ImpvaG5kb2VAZXhhbXBsZS5jb20iLCJ1c2VyX2xldmVsX2lkIjoyLCJpYXQiOjE3MDA2NDUxMDN9.FK9V6YOw8BOYjiRW2R6irkb3S0NM3X5gdwB5sKRv61U
content-type: application/json

  {
    "user_id": 8,
    "filename": "updated.jpg",
    "size": 123456,
    "title": "updated",
    "description": "updated",
    "mimetype": 1
  }

### DELETE /media/:id
DELETE http://127.0.0.1:3000/api/media/15
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6IkpvaG5Eb2UiLCJlbWFpbCI6ImpvaG5kb2VAZXhhbXBsZS5jb20iLCJ1c2VyX2xldmVsX2lkIjoyLCJpYXQiOjE3MDA2NDUxMDN9.FK9V6YOw8BOYjiRW2R6irkb3S0NM3X5gdwB5sKRv61U

// -----------------------User-----------------------

GET http://127.0.0.1:3000/

### GET /users
GET http://127.0.0.1:3000/api/user

### GET /users/:id
GET http://127.0.0.1:3000/api/user/6

### POST /user
POST http://127.0.0.1:3000/api/user
content-type: application/json

  {
    "user_id": 3609362,
    "username": "toimiiko",
    "password": "********",
    "email": "toimiihan@pliis.com",
    "user_level_id": 1,
    "created_at": "2023-04-02T05:56:41.000Z"
  }

### POST /user error
POST http://127.0.0.1:3000/api/user

{"höpö": "höpö"}

### PUT /users/:id
PUT http://127.0.0.1:3000/api/user/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6IkpvaG5Eb2UiLCJlbWFpbCI6ImpvaG5kb2VAZXhhbXBsZS5jb20iLCJ1c2VyX2xldmVsX2lkIjoyLCJpYXQiOjE3MDA2NTMyNzl9.wBG_mB9kx40iMANZf1rqb3ylOQwFgPYCy-RwHhhFJtI
content-type: application/json

  {
    "user_id": 3609362,
    "username": "testi",
    "password": "*******",
    "email": "testitit@example.com",
    "user_level_id": 3,
    "created_at": "2023-04-02T05:56:41.000Z"
  }

### DELETE /users/:id
DELETE http://127.0.0.1:3000/api/user/7