### GET / 
GET http://127.0.0.1:3000/

### GET /items
GET http://127.0.0.1:3000/api/media

### GET /items/:id
GET http://127.0.0.1:3000/api/media/9632

### POST /items
POST http://127.0.0.1:3000/api/media
content-type: application/json

  {
    "media_id": 0,
    "filename": "testi.jpg",
    "filesize": 239,
    "title": "KEllari",
    "description": "kkekekek",
    "user_id": 307655,
    "media_type": "image/jpeg",
    "created_at": "2018-10-12T06:56:41.000Z"
  }

### POST /items error
POST http://127.0.0.1:3000/api/media

{"höpö": "höpö"}

### PUT /items/:id
PUT http://127.0.0.1:3000/api/media/0
content-type: application/json

  {
    "media_id": 0,
    "filename": "updated.jpg",
    "filesize": 239,
    "title": "updated",
    "description": "updated",
    "user_id": 307655,
    "media_type": "image/jpeg",
    "created_at": "2018-10-12T06:56:41.000Z"
  }

### DELETE /items/:id
DELETE http://127.0.0.1:3000/api/media/0

// -----------------------User-----------------------

GET http://127.0.0.1:3000/

### GET /items
GET http://127.0.0.1:3000/api/user

### GET /items/:id
GET http://127.0.0.1:3000/api/user/260

### POST /items
POST http://127.0.0.1:3000/api/user
content-type: application/json

  {
    "user_id": 3609362,
    "username": "TESTIKÄYTTÄJÄ",
    "password": "********",
    "email": "TESTIKÄYTTÄJÄ@example.com",
    "user_level_id": 3,
    "created_at": "2023-04-02T05:56:41.000Z"
  }

### POST /items error
POST http://127.0.0.1:3000/api/user

{"höpö": "höpö"}

### PUT /items/:id
PUT http://127.0.0.1:3000/api/user/0
content-type: application/json

  {
    "user_id": 3609362,
    "username": "updated",
    "password": "********",
    "email": "updated@example.com",
    "user_level_id": 3,
    "created_at": "2023-04-02T05:56:41.000Z"
  }

### DELETE /items/:id
DELETE http://127.0.0.1:3000/api/user/0